### ISSUE TITLE
SkidRightLayoutManager滑动或者双击时很容易OOM，还没看代码

### ISSUE THREAD

**Issue by qingtianyue** [DingMouRen/LayoutManagerGroup#57]
2019-08-20 17:21:51.446 28820-28850/com.dingmouren.example.layoutmanagergroup E/PriorityExecutor: Request threw uncaught throwable
    java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 13639692 byte allocation with 11547552 free bytes and 11MB until OOM
        at java.util.concurrent.FutureTask.report(FutureTask.java:94)
        at java.util.concurrent.FutureTask.get(FutureTask.java:164)
        at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1141)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
        at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 13639692 byte allocation with 11547552 free bytes and 11MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:905)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:882)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:849)
        at com.bumptech.glide.load.resource.bitmap.TransformationUtils.centerCrop(TransformationUtils.java:62)
        at com.bumptech.glide.load.resource.bitmap.CenterCrop.transform(CenterCrop.java:30)
        at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:54)
        at com.bumptech.glide.load.engine.DecodeJob.transform(DecodeJob.java:236)
        at com.bumptech.glide.load.engine.DecodeJob.transformEncodeAndTranscode(DecodeJob.java:139)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:129)
        at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
        at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
        at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
        at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)

**Comment by jackson0415** [comment]
我只有在改为左滑的时候，出现OOM，正常右边hua倒是没有出现过
